# -*- coding: utf-8 -*-
"""Dow_DIA_from2009.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DIP0EdyReaArmd-1-vYIZ6CkAcupaRPT
"""

pip install yfinance

import pandas as pd
import yfinance as yf
import matplotlib.pyplot as plt
from sklearn import linear_model

d = yf.download("DIA", start="2009-03-01", end="2021-04-30")
print(d)
#d.to_csv("/content/Dow_DIA_from2009.csv")
df = pd.read_csv("/content/Dow_DIA_from2009.csv")
print("")
print(df)

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
plt.xlabel("Days")
plt.ylabel("Price (US$)")
plt.scatter(df["Days"], df["Open"])

reg = linear_model.LinearRegression()
reg.fit(df[["Days"]], df["Open"])

print(reg.predict([[3063]]))