# -*- coding: utf-8 -*-
"""Polyreg_BTC_4months.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14ypE0PoJ-cmVWc0eJFaCvMPUD74qNtxK
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

pip install yfinance

import yfinance as yf
p = yf.download("BTC-USD", start = "2021-01-01", end = "2021-04-30")
df = pd.read_csv("/content/BTC 4 month data_og.csv")
#p.to_csv("/content/BTC 4 month data.csv")
print(df)

x = df["Days"].values
y = df["Adj Close"].values

x = x.reshape(-1,1)

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
plt.scatter(df["Days"], df["Adj Close"])

poly = PolynomialFeatures(degree = 9)
x_poly = poly.fit_transform(x)

poly.fit(x_poly, y)

lin = LinearRegression()
lin.fit(x_poly, y)
y_pred = lin.predict(x_poly)

plt.scatter(df["Days"], df["Adj Close"])
plt.plot(y_pred, color = "red")

r2_score(y,y_pred)