# -*- coding: utf-8 -*-
"""Polyreg_BTC.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14ypE0PoJ-cmVWc0eJFaCvMPUD74qNtxK
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures

df = pd.read_csv("/content/BTC 2 Months.csv")
print(df)

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
plt.scatter( df["Days"], df["Adj Close"])

x = df["Days"].values
y = df["Adj Close"].values

print(x)
print(y)

x = x.reshape(-1,1)
print(x)

poly = PolynomialFeatures(degree = 4)

x_poly = poly.fit_transform(x)

poly.fit(x_poly, y)

lin = LinearRegression()
lin.fit(x_poly, y)

y_pred = lin.predict(x_poly)
print(y_pred)

plt.scatter(x,y, color = "Blue")
plt.plot(y_pred, color = "Red")

from sklearn.metrics import r2_score, mean_squared_error
r2_score(y,y_pred)