# -*- coding: utf-8 -*-
"""vfv_mult_LR.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DIP0EdyReaArmd-1-vYIZ6CkAcupaRPT
"""

import pandas as pd
import numpy as np

df = pd.read_csv("/content/vfv_for_mult_LR.csv")
print(df)

x = df.drop(["Adj Close"], axis = 1).values
y = df["Adj Close"].values

print(x)
print("")
print(y)

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y, test_size = 0.7, random_state = 0)

from sklearn.linear_model import LinearRegression
ml = LinearRegression()
ml.fit(x_train,y_train)

print(ml.predict(x_test))

print(ml.predict([[24.72999954,	24.72999954,	24.69000053,	24.69000053]]))

"""Model Evaluation R2score"""

from sklearn.metrics import r2_score
r2_score(y_test,ml.predict(x_test))

import matplotlib.pyplot as plt
plt.figure(figsize=(15,10))
plt.scatter(y_test,ml.predict(x_test))
plt.xlabel("Actual")
plt.ylabel("Predicted")
plt.title("Actual v/s Predicted")

diff = pd.DataFrame({"Actual Value":y_test, "Predicted Value":ml.predict(x_test), "Difference": y_test-ml.predict(x_test)})
diff[0:20]